### ISSUE TITLE
Support for multiple octet characters (UTF-8) is broken

### ISSUE THREAD

**Issue by WLR86** [GermainZ/weechat-vimode#77]
Steps to reproduce : 
Ensure WeeChat is set to UTF-8 encoding
Paste the following

> Thè quïck brôwn fox jùmps över thé lâzy dôg

Then use 'w' and 'b' to move around and see where the cursor goes
(WeeChat version 2.4)

**Comment by GermainZ** [comment]
Thanks for reporting! This should already be fixed in the git version.

I should submit an update to the WeeChat scripts repo. :)

**Comment by WLR86** [comment]
Oh, great ! 
Thanks for your time and effort, this is much appreciated :smile:

**Comment by WLR86** [comment]
Using git version right now (replaced the one I got from the repo) and still having the same issue (version number is 0.7 looks like you forgot to increment it - this might be required prior to pushing the code to the WeeChat scripts repository) - Am I missing something here ?

**Comment by GermainZ** [comment]
Ah, sorry -- seems to work with Python3 but not Python2. My mistake for not properly testing this :)

(I usually increment the version just before submitting an update to the repo.)
